master:
  image: gettyimages/spark:1.6.1-hadoop-2.6
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 8081:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

worker:
  image: gettyimages/spark:1.6.1-hadoop-2.6
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data

zeppelin:
  image: rootree/zeppelin
  hostname: zeppelin
  environment:
    ZEPPELIN_PORT: 8090
    ZEPPELIN_JAVA_OPTS: "-Dspark.driver.port=5432"
    SPARK_SUBMIT_OPTIONS: "--packages org.apache.hadoop:hadoop-aws:2.6.3"
    MASTER: spark://master:7077
  links:
    - master
  expose:
    - 5432
  ports:
    - 8090:8090
    - 8091:8091
  volumes:
    - ./data:/zeppelin/data
    - ./notebooks:/usr/zeppelin/notebook
